### ISSUE TITLE
Login causes in White page

### ISSUE THREAD

**Issue by ghost** [BlackCetha/SteamAuthOOP#1]
Hi,

maybe someone can help me out. If I try to login it will redirect me to the steam login page. This is normal but after logging in it´s redirect me back to the domain but now I have a white blank page.
I don´t know what I made wrong maybe someone had this error to and can help me out.

Thanks in advance

Kind regards
Thymopat

**Comment by BlackCetha** [comment]
Could you provide some code samples?

**Comment by BlackCetha** [comment]
Since you have that problem with other libraries too, i would say the issues are within your code, not the library. Check what your page does if the user is logged in.

**Comment by ghost** [comment]
Maybe you have an idea how to check for problems?

Sorry, you are right I posted the same question on another projekt too. I hoped to get here more help.
So I can close the other one, because here I get help :D

**Comment by ghost** [comment]
Here is a code example:

``` php
<?php   
    require ('inc/steamauthOOP.class.php'); 
    $steam = new steamauthOOP();
    if (isset($_GET["logout"])) {
    $steam->logout();
    }
    include ("inc/functions.php");
    require_once ("inc/database.php");
    include ("inc/mysqli_queries.inc.php");

    if(!$steam->loggedIn())
    {
        include("views/index.php");
    }
    else
    {
        check_declare();
        get_error_success();
        database_additional();
        check_usersetup();
        check_previleges();
            // Closing sql connection
            mysqli_close($connect);
        include("views/secure_index.php");
    }
?>
```

How can I format it the right way?
Ok found the solution.

**Comment by BlackCetha** [comment]
`Ok found the solution.`

So you fixed it?

**Comment by ghost** [comment]
No I mean I know how to format the code examples.

The Problem: I can´t find the issue in my code example. 

Maybe you can give me a tip how to start here to search for the error. 
What would you do in this situation?

**Comment by BlackCetha** [comment]
Comment out your functions one by one and test it.

**Comment by ghost** [comment]
Nice idea I´ll test it.

**Comment by ghost** [comment]
At the moment I can´t test it because of my dorm. I have here a bad internet connection, but on the weekend it will be possible.

**Comment by ghost** [comment]
Crazy there is really a functions, which cause this bug. Thanks BlackCetha for your help.

Kind Regards
Thymopat
