### ISSUE TITLE
Error with login->return

### ISSUE THREAD

**Issue by FlashModz** [BlackCetha/SteamAuthOOP#14]
Hello,

I tested your code with mine.
The problem is that when this connection valid with steam, it does not redirect to my web space.

it tells me instead a simple message that says: error.
An idea on the ask ?

my allow_url_fopen is enabled and validated.

Thanks :)
Screen of the return value : http://prntscr.com/h61di2

**Comment by BlackCetha** [comment]
That happens when there's something wrong with your loginpage setting.
Maybe there is a typo in there or it isn't pointing to the same domain name as you are coming from.

**Comment by FlashModz** [comment]
Yes, i'm set login.php into return settings.
i'm deleted this parameters and work !

Thanks bro,
