### ISSUE TITLE
file get content convert to curl

### ISSUE THREAD

**Issue by cristal2431** [BlackCetha/SteamAuthOOP#15]
I want to convert file_get_content to use curl under validate(). Can you suggest some example? I am getting error in this part as its returning null.

**Comment by BlackCetha** [comment]
`file_get_contents()` is far easier to use. The only reason to change it to use cUrl would be to support hosters which disabled `allow_url_fopen`.
You can ask your hoster to enable it for your account or rewrite the part yourself using the official docs.

While I have no personal experience with using cUrl, I've seen implementations using it cause problems in other projects.

**Comment by cristal2431** [comment]
Yes, I am aware that file_get_contents() is far easier to use. But I have requirement to use curl due to server. Enabling it is not an option.
