### ISSUE TITLE
Steam Login Session

### ISSUE THREAD

**Issue by frkncck** [BlackCetha/SteamAuthOOP#19]
I edited config and click the login text. After it returns to my web site but session not working.

                  require("steamauthOOP.class.php");
                  $steam = new SteamAuthOOP();
                  if ($steam->loggedIn()) {
                    echo $steam->personaname;
                  } else {
                    echo "<a href='".$steam->loginUrl()."'>Login</a>";
                  }

**Comment by BlackCetha** [comment]
Since you posted the same issue over in Smith197/SteamAuthentication, I believe it must be an issue with your configuration. See my comment there.

https://github.com/SmItH197/SteamAuthentication/issues/221
