### ISSUE TITLE
How to use url + parameters

### ISSUE THREAD

**Issue by ghost** [BlackCetha/SteamAuthOOP#2]
Hi again,

I have the next problem.
If I try to login from example here:
domain.tld/profile.php?id=0123456789
than I will get a blank page, because there are no parameters.
I need the parameters to get the profile informations.
Ok I can make there an error page, but it´s poor for the people who log in.
How can I login with url + parmeters?

Thanks in advance
Kind Regards 
Thymopat

**Comment by BlackCetha** [comment]
You can either redirect the user back to the main page upon login or just cache the parameters inside $_SESSION.
