### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by lRoberth** [BlackCetha/SteamAuthOOP#20]
On login it redirects you to the same site but with a lot of data in the searchbar
[https://i.imgur.com/uxDBHTa.png](https://i.imgur.com/uxDBHTa.png)

(Yes, I know this is years old)

**Comment by BlackCetha** [comment]
Yes, that is how it is supposed to work.
This library hasn't been updated in years because it never broke.
Are you sure you have it installed correctly?

**Comment by BlackCetha** [comment]
Closing because there was no answer in five days.

**Comment by x3rt** [comment]
Possibly re-open.
Does not work on PHP8 but works in PHP7

**Comment by BlackCetha** [comment]
Thats a seperate issue then

**Comment by lRoberth** [comment]
Pretty sure it’s related to the main issue.
