### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by SPooCK** [BlackCetha/SteamAuthOOP#3]
Hi, I'm trying to use your API which is great, but there is a problem which I'm unable to sort out... When I try to login it will redirect me to the steam login page and after logging in it´s redirect me back but the problem now is that I have a white blank page. I'm not using any other additional functions or anything, just your original code used in 1 PHP file. (tried with separate same problems) The thing is I've tried in several other hosts and your API worked just fine, but in this host which I'm trying to use it won't work and I will be stuck on a blank white page and the Steam Key is fully registered to the website. I have live example here: http://echovalleyserver.com/e107_plugins/ipn_donate_menu/ipn_steam.php and the content of the ipn_steam.php file cant be found here: https://gist.github.com/SPooCK/08f1c97cf9b508ca72f9 I'm using e107 v2 hosted at https://hostmonster.com/ and not sure but maybe something is blocking it. Tried all possible access point which I can think of but no result. Maybe you can give me some light on this problem.

**Comment by BlackCetha** [comment]
Hi!
Firstly, make sure that you don't post your API-key. You only have 10,000 calls per day and if it gets stolen the abuser is likely to reach that limit every day. You can regenerate your key here: http://steamcommunity.com/dev/apikey

It's probably your host blocking the file_get_contents() function that gets the data from steam.
You can try removing the @ in front of it (its used to block error messages from that line in order to keep your key secret) and see if any error messages pop up.
Your hoster has likely disabled `allow_url_fopen` in PHP. You can try and ask the support to change that. If they don't do that you eventually have to change to another host.

**Comment by SPooCK** [comment]
Yeah, I forgot about the Steam Key thanks, but anyway its neither from @ because I removed all the @ and checked the php.ini and allow_url_fopen is On as I have full access to all the server core files but is still returning blank page. It's very strange because I really can't find what is blocking it or where is the problem.

**Comment by BlackCetha** [comment]
Did you try if the demo file works?

**Comment by SPooCK** [comment]
All the files works just fine in other host even the one that I've merged both code into 1 its just that host is something wrong with it or something is blocking the API don't know really. I've been using your API since the host was on e107 v1 then I updated to v2 and suddenly stopped working. Really strange.

**Comment by BlackCetha** [comment]
You might want to try the demo file on the current host.

**Comment by SPooCK** [comment]
Excuse me, you probably misunderstood me, but that's what I was saying that if tried every possible method, but the outcome was the same even switched to different Steam APIs that are more simplified but still a blank page... Something goes wrong when is returning me from the Steam Login page and this happens in like 3 more different Steam APIs like yours.

**Comment by BlackCetha** [comment]
Thats not what I'm asking you to do. There is the file `demo.php` in the SteamAuthOOP folder.
Try if that one works.

**Comment by SPooCK** [comment]
Oh, sorry but yes the demo.php is fully working http://echovalleyserver.com/demo.php still I'm not able to use the code as I want to display in a proper page sorted in a box.

Edit: Ok found the problem it is in require_once ("../../class2.php"); removing that line make the code work again although i dont know what can be wrong in it... https://github.com/e107inc/e107/blob/master/class2.php

**Comment by SPooCK** [comment]
I've managed to find a temporary solution for this mostly like work around with redirecting pages, but it's working for the time being.

<?php
require ('steamauthOOP.class.php');  
$steam = new steamauthOOP();
if (isset($_GET["logout"])) {
    $steam->logout();
    header("Location: http://echovalleyserver.com/e107_plugins/ipn_donate_menu/ipn_steam.php");
    die();
}
if (isset($_GET["openid_assoc_handle"])) {
    header("Location: http://echovalleyserver.com/e107_plugins/ipn_donate_menu/ipn_steam.php");
    die();
}
?>

--- Then using the data in my WebSite ---
include ('../../SteamRED.php');
require_once ("../../class2.php");
require_once (HEADERF);

if(!$steam->loggedIn()) {
....
