### ISSUE TITLE
Steam login

### ISSUE THREAD

**Issue by asilvach** [BlackCetha/SteamAuthOOP#7]
Hi. 
I have in the past the Steamauth by SmItH197, and now i am testing your login but this have the same problem sometimes, is not a open ID but you login and this bug on the process... You can see on csgotwo.com and test ...
Waiting for reply ;)
André Silva

**Comment by BlackCetha** [comment]
You must be still using SteamAuth by SmIth197. My library has the values needed hardcoded in it and therefore cant break in this way.
