### ISSUE TITLE
Demo.php redirect issues

### ISSUE THREAD

**Issue by Sebastian99** [BlackCetha/SteamAuthOOP#9]
Hello,
i have the following problem: When I want to try the demo and i try to log me in it Says Error! (http://prntscr.com/bond6u)
My Config:
        "apikey" => "XXXXXXXXXXXXXXXXX",
        "domainname" => "zwetschkenroester.li", // Displayed domain in the login-screen
        "loginpage" => "var/www/html/demo.php", // path on my VPS (I also tried demo.php)
        "logoutpage" => "",
        "skipAPI" => false // true = dont get the data from steam, just return the steamid64

You can try it yourself: zwetschkenroester.li

LG
 Sebastian

**Comment by BlackCetha** [comment]
Both `loginpage` and `logoutpage` will base on the browsers perspective, not your filesystem.
Wich means you will have to change `loginpage` to `/demo.php`.

**Comment by Sebastian99** [comment]
Thanks for your awnser! I changed it to "/demo.php" but it doesn't work! The same Error!

**Comment by bduman** [comment]
I got same error. When i set empty of loginpage. It works.
